library(ggplot2)
library(GGally)
library(scales)
library(memisc)
ggplot(iris, aes(x = Species)) + geom_bar(fill = "dark blue", colour = "white")
ggplot(iris, aes(x = Sepal.Length)) + geom_histogram(fill = "pink", colour = "white")
ggplot(iris, aes(x = Sepal.Length, y = Petal.Width, color = Species)) + geom_point() 
ggplot(iris, aes(x = Species, y = Petal.Width)) + geom_boxplot(fill = "sky blue")
ggpairs(iris)